// Evidence database (spec §3.3 Evidence Library). Every item is a real,
// dated artifact with an outbound link to its source (Appendix B of the spec).
// This seeds the Database mode; media payloads and "show on globe"
// cross-links come later.

export type EvidenceCategory =
  | 'report'
  | 'dataset'
  | 'audio'
  | 'analysis'
  | 'event'

export interface EvidenceItem {
  id: string
  /** ISO date (UTC) the artifact was published / the event occurred. */
  date: string
  title: string
  publisher: string
  category: EvidenceCategory
  desc: string
  url: string
  /** Layer ids this item supports (future "show on globe" action). */
  layers?: string[]
}

export const CATEGORY_META: Record<EvidenceCategory, { label: string }> = {
  report: { label: 'REPORT' },
  dataset: { label: 'DATASET' },
  audio: { label: 'AUDIO' },
  analysis: { label: 'ANALYSIS' },
  event: { label: 'EVENT' },
}

export const EVIDENCE: EvidenceItem[] = [
  {
    id: 'disappearance',
    date: '2014-03-08',
    title: 'MH370 disappears',
    publisher: 'Event',
    category: 'event',
    desc: 'Last ADS-B position near IGARI at 17:21 UTC (7 March); final SATCOM log-on 00:19 UTC (8 March). 239 people aboard.',
    url: 'https://www.mot.gov.my/en/aviation/reports/archived-report/mh370',
    layers: ['flight-epoch1', 'flight-epoch2', 'arcs'],
  },
  {
    id: 'najib-announcement',
    date: '2014-03-24',
    title: '"Flight MH370 ended in the southern Indian Ocean"',
    publisher: 'Event · PM Najib Razak',
    category: 'event',
    desc: 'Based on refined Inmarsat BFO analysis, Malaysia\'s Prime Minister announced the flight ended in the southern Indian Ocean, far from any landing site. The search pivoted south for good.',
    url: 'https://www.aljazeera.com/news/2015/8/5/malaysia-pm-confirms-wreckage-belongs-to-mh370',
    layers: ['arcs'],
  },
  {
    id: 'preliminary-report',
    date: '2014-04-09',
    title: 'Preliminary report (incl. ATC transcript)',
    publisher: 'Malaysia MOT / ICAO',
    category: 'report',
    desc: 'First official report; contains the authoritative ATC communications transcript.',
    url: 'https://www.icao.int/sites/default/files/safety/airnavigation/AIG/Documents/Safety-Recommendations-to-ICAO/Final-Reports/MOT_KIKU_9M-MRO_01-2014_preliminary_report.pdf',
  },
  {
    id: 'atc-audio',
    date: '2014-05-01',
    title: 'ATC radio recordings released (~7 min)',
    publisher: 'Malaysia DCA',
    category: 'audio',
    desc: 'Delivery, Ground, Tower and Lumpur Radar segments, ending with "Good night, Malaysian three seven zero" at 17:19:30 UTC.',
    url: 'https://www.nbcnews.com/storyline/missing-jet/listen-missing-jet-mh370-pilots-talking-air-traffic-control-n94716',
    layers: ['flight-epoch1'],
  },
  {
    id: 'inmarsat-log',
    date: '2014-05-27',
    title: 'Inmarsat SATCOM log released (47 pp)',
    publisher: 'Malaysia DCA / Inmarsat',
    category: 'dataset',
    desc: 'The BTO/BFO communications log defining the seven handshake arcs. Validated CSV conversion available (davetaz/mh370-data).',
    url: 'https://github.com/davetaz/mh370-data',
    layers: ['arcs'],
  },
  {
    id: 'curtin-acoustic',
    date: '2014-06-04',
    title: 'Hydroacoustic analysis (HA01 Cape Leeuwin)',
    publisher: 'Curtin University CMST',
    category: 'analysis',
    desc: 'Candidate low-frequency event recorded on IMOS/CTBTO hydrophones, timing broadly consistent with the 7th arc; high uncertainty.',
    url: 'http://cmst.curtin.edu.au/wp-content/uploads/sites/4/2016/03/duncan_sound_clue_in_hunt_for_MH370_jun14.pdf',
    layers: ['poi'],
  },
  {
    id: 'atsb-definition',
    date: '2014-08-18',
    title: 'Definition of Underwater Search Areas',
    publisher: 'ATSB',
    category: 'report',
    desc: 'BTO/BFO-based definition of the southern Indian Ocean priority area (updated 3 Dec 2015).',
    url: 'https://www.atsb.gov.au/mh370-pages/updates/reports',
    layers: ['search', 'arcs'],
  },
  {
    id: 'accident-declaration',
    date: '2015-01-29',
    title: 'Malaysia declares MH370 an accident',
    publisher: 'Event · Malaysia DCA',
    category: 'event',
    desc: 'The flight\'s status was formally changed to "accident" under ICAO Annex 13; all 239 aboard (227 passengers, 12 crew) presumed lost. The declaration enabled compensation proceedings for next-of-kin.',
    url: 'https://en.wikipedia.org/wiki/Malaysia_Airlines_Flight_370',
  },
  {
    id: 'ashton-2015',
    date: '2015-01-01',
    title: '"The Search for MH370" (Ashton et al.)',
    publisher: 'Journal of Navigation 68(1), open access',
    category: 'analysis',
    desc: 'The satellite-communications methodology: BTO/BFO measurements, satellite ephemeris, and the log-on BTO correction behind the arcs.',
    url: 'https://www.cambridge.org/core/journals/journal-of-navigation/article/search-for-mh370/D2D1C4C99E7BFDE35841CFD70081114A',
    layers: ['arcs'],
  },
  {
    id: 'factual-information',
    date: '2015-03-08',
    title: 'Factual Information report',
    publisher: 'Malaysian ICAO Annex 13 Team',
    category: 'report',
    desc: 'Detailed factual record at one year: radar data, aircraft systems, crew, cargo. Primary source for the Epoch 1-2 track figures.',
    url: 'https://www.mot.gov.my/en/Laporan%20MH%20370/Factual%20Information%20Safety%20Investigation%20For%20MH370.pdf',
    layers: ['flight-epoch1', 'flight-epoch2'],
  },
  {
    id: 'flaperon',
    date: '2015-07-29',
    title: 'Flaperon found on Réunion',
    publisher: 'Event · confirmed 9M-MRO',
    category: 'event',
    desc: 'First recovered debris. PM Najib announced experts had "conclusively confirmed" it as MH370\'s on 5 August 2015; the Paris prosecutor\'s office stated certainty on 3 September 2015 after a serial-number match at DGA Toulouse.',
    url: 'https://www.atsb.gov.au/publications/investigation_reports/2014/aair/ae-2014-054',
    layers: ['debris', 'drift'],
  },
  {
    id: 'first-principles',
    date: '2016-12-20',
    title: 'First Principles Review',
    publisher: 'ATSB',
    category: 'report',
    desc: 'Expert re-examination of all evidence; recommended a new 25,000 km² area to the north of the searched zone.',
    url: 'https://www.atsb.gov.au/sites/default/files/media/5772107/ae2014054_final-first-principles-report.pdf',
    layers: ['search'],
  },
  {
    id: 'csiro-drift-1',
    date: '2016-12-08',
    title: 'CSIRO drift modelling, Part I (of IV)',
    publisher: 'CSIRO for ATSB',
    category: 'analysis',
    desc: 'Ocean-drift simulations from candidate 7th-arc origins tested against debris find locations and timing. Parts II-IV followed in 2017.',
    url: 'http://www.marine.csiro.au/~griffin/MH370/',
    layers: ['drift', 'debris'],
  },
  {
    id: 'debris-reports',
    date: '2017-02-28',
    title: 'Debris examination reports',
    publisher: 'Malaysia MOT',
    category: 'report',
    desc: 'Item-by-item examination of recovered debris: find locations, part identification, confirmation status.',
    url: 'https://www.mot.gov.my/en/Laporan%20MH%20370/Debris%20Examination%20Reports%20-%2028Feb2017.pdf',
    layers: ['debris'],
  },
  {
    id: 'operational-search',
    date: '2017-10-03',
    title: 'The Operational Search for MH370 (final, 440 pp)',
    publisher: 'ATSB',
    category: 'report',
    desc: 'Complete record of the 2014-17 surface and underwater searches, incl. Curtin acoustic reports (App. H & I) and bathymetry program.',
    url: 'https://www.atsb.gov.au/sites/default/files/media/5773565/operational-search-for-mh370_final_3oct2017.pdf',
    layers: ['search', 'bathymetry'],
  },
  {
    id: 'ga-bathymetry',
    date: '2017-07-19',
    title: 'MH370 Phase 1 bathymetry data release',
    publisher: 'Geoscience Australia',
    category: 'dataset',
    desc: '278,000 km² of high-resolution seabed mapping from the search, openly released (CC BY 4.0).',
    url: 'https://www.ga.gov.au/about/projects/marine/mh370-data-release',
    layers: ['bathymetry'],
  },
  {
    id: 'search-suspension',
    date: '2017-01-17',
    title: 'Tripartite underwater search suspended',
    publisher: 'Event · Malaysia / Australia / China',
    category: 'event',
    desc: 'The 120,000 km² underwater search was suspended after nearly three years without a find, per the tripartite agreement that it would not continue absent "credible new evidence".',
    url: 'https://en.wikipedia.org/wiki/Search_for_Malaysia_Airlines_Flight_370',
    layers: ['search'],
  },
  {
    id: 'oi-2018',
    date: '2018-01-22',
    title: 'Ocean Infinity search (Seabed Constructor)',
    publisher: 'Ocean Infinity / Malaysia',
    category: 'event',
    desc: 'No-find-no-fee AUV search of >112,000 km² along the 7th arc; planned end 29 May 2018 (minister Loke), reported ended unsuccessfully 9 June 2018.',
    url: 'https://oceaninfinity.com/news/',
    layers: ['search'],
  },
  {
    id: 'spoiler-analysis-2021',
    date: '2021-03-07',
    title: 'Right-wing spoiler fragment analysis (Jeffreys Bay)',
    publisher: 'Exner & Thompson (independent)',
    category: 'analysis',
    desc: 'A fragment found at Jeffreys Bay, South Africa (Aug 2020) was identified as spoiler #8 or #9 from a 777 right wing, almost certainly MH370; its fracture pattern suggests separation during a high-speed final descent.',
    url: 'https://mh370.radiantphysics.com/2021/03/07/two-new-reports-on-mh370-debris-suggest-a-high-speed-final-descent/',
    layers: ['debris'],
  },
  {
    id: 'tataly-debris-report',
    date: '2022-12-12',
    title: 'Landing-gear-door debris claim (disputed)',
    publisher: 'Godfrey & Gibson · disputed by Iannello et al.',
    category: 'analysis',
    desc: 'Report claimed a piece kept by a Madagascar fisherman since 2017 was the left main gear trunnion door with penetration damage implying gear extended at impact. Rebutted within days (wrong size, missing features); later reassessed as likely a flap/slat fragment.',
    url: 'https://mh370.radiantphysics.com/2022/12/18/new-mh370-debris-not-from-landing-gear-door/',
    layers: ['debris'],
  },
  {
    id: 'sir-2018',
    date: '2018-07-30',
    title: 'Safety Investigation Report (495 pp)',
    publisher: 'Malaysian ICAO Annex 13 Team',
    category: 'report',
    desc: 'The final Malaysian investigation report: full factual record, analysis, and the authoritative radar track appendices.',
    url: 'https://www.mot.gov.my/en/MH370%20Investigation%20Report/01-Report/MH370SafetyInvestigationReport.pdf',
    layers: ['flight-epoch1', 'flight-epoch2', 'arcs', 'debris'],
  },
  {
    id: 'data-review-2022',
    date: '2022-03-31',
    title: 'MH370 Data Review',
    publisher: 'Geoscience Australia / ATSB',
    category: 'report',
    desc: 'Review of sonar contacts and data quality from the completed search areas.',
    url: 'https://www.atsb.gov.au/sites/default/files/2024-02/mh370-data-review-2022-final-report-v2.pdf',
    layers: ['search', 'bathymetry'],
  },
  {
    id: 'oi-resumption',
    date: '2025-12-30',
    title: 'Search resumption announced (2025-26)',
    publisher: 'Malaysia MOT / Ocean Infinity',
    category: 'event',
    desc: 'New 15,000 km² zone along the 7th arc under a no-find-no-fee agreement; ~7,571 km² surveyed across two campaigns.',
    url: 'https://www.mot.gov.my/en/Kenyataan%20Media/Year%202025/MEDIA%20RELEASE%20RESUMPTION%20OF%20MH370%20SEARCH%20BY%20OCEAN%20INFINITY%20IN%20THE%20SOUTHERN%20INDIAN%20OCEAN.pdf',
    layers: ['search'],
  },
  {
    id: 'oi-conclusion',
    date: '2026-03-08',
    title: 'Ocean Infinity concludes 2025-26 campaign',
    publisher: 'Ocean Infinity',
    category: 'event',
    desc: 'Vessel departed the search area 23 January 2026; 7,571 km² surveyed this campaign, 151 days at sea and >140,000 km² mapped since 2018. CEO Plunkett: "we can say with confidence that it isn\'t where we looked."',
    url: 'https://oceaninfinity.com/news/conclusion-of-the-search-for-malaysian-airlines-flight-mh370/',
    layers: ['search'],
  },
  {
    id: 'ugib-2020',
    date: '2020-03-07',
    title: '"The Final Resting Place of MH370" (UGIB 2020)',
    publisher: 'Ulich, Godfrey, Iannello & Banks (independent)',
    category: 'analysis',
    desc: 'Independent-group best-fit reconstruction: an LNAV route due south from waypoint BEDAX giving a last estimated position of 34.2342°S 93.7875°E on the 7th arc. Anchors the 2025-26 search zone.',
    url: 'https://mh370.radiantphysics.com/papers/',
    layers: ['flight-epoch3', 'candidate-sites'],
  },
  {
    id: 'captio-analysis-2022',
    date: '2022-06-24',
    title: 'CAPTIO reconstruction (Blelly & Marchand)',
    publisher: 'Patrick Blelly & Jean-Luc Marchand / CAPTIO',
    category: 'analysis',
    desc: 'A piloted-to-the-end reconstruction: FL300 / Mach 0.706 southern leg fitting the 7 arcs plus 3 extra Inmarsat constraints (the 18:28 BTO ring and the 18:40 & 23:14 BFO calls, all omitted from official analyses), ending in a controlled ditching. Proposes a new search zone south of the 2018 corridor.',
    url: 'https://www.mh370-caption.net/wp-content/uploads/Blelly-Analysis-of-Flight-MH370.pdf',
    layers: ['flight-epoch3', 'aux-arcs', 'candidate-sites', 'search'],
  },
  {
    id: 'captio-encounters-2025',
    date: '2025-04-06',
    title: 'Possible MH370 encounters after the FMT (CAPTIO)',
    publisher: 'Jean-Luc Marchand & Patrick Blelly / CAPTIO',
    category: 'analysis',
    desc: 'FlightAware traffic analysis showing that, on the CAPTIO trajectory, MH370 passed ~12 NM below a two-ship formation - Emirates EK407 above Etihad EY461 - near airway N509 at ~20:02 UTC; neither reported seeing it, which CAPTIO read as lights-off on a moonless night. Model-dependent.',
    url: 'https://www.mh370-caption.net/wp-content/uploads/Caption-analysis-MH370-flights-after-FMT.pdf',
    layers: ['flight-epoch3', 'poi'],
  },
  {
    id: 'oi-extension-2026',
    date: '2026-07-01',
    title: 'Search agreement extended to 30 June 2027',
    publisher: 'Malaysia MOT / Ocean Infinity',
    category: 'event',
    desc: '12-month extension of the no-find-no-fee agreement (~USD 70M on success); ~7,428 km² remain to scan, with operations paused for the southern winter Nov 2026 - Apr 2027.',
    url: 'https://airlive.net/news/2026/07/04/malaysian-government-extended-agreement-with-ocean-infinity-for-another-12-months-to-continue-the-search-for-mh370/',
    layers: ['search'],
  },
]

/** Sorted ascending by date. */
export const EVIDENCE_SORTED = [...EVIDENCE].sort((a, b) =>
  a.date.localeCompare(b.date),
)
